### ISSUE TITLE
一个小缺陷

### ISSUE THREAD

**Issue by dengchenglin** [bawn/Shazam#2]
1、将第一个childscrollView上滑到老远
2、点击Menu切换至另一个childscrollView，下滑childscrollView使header和Menu恢复至原状
3、点击Menu切回第一个childscrollView
此时触摸header往下滑，header不会跟着往下滑，只有下面的childscrollView会跟着下滑直到childscrollView偏移为0时 header才能正常滑动

**Comment by dengchenglin** [comment]
所以在切换Menu时还是得将所有childscrollView的offest恢复成zero才行啊

**Comment by bawn** [comment]
@dengchenglin 这个问题，可以说是缺陷也可以说是feature，事实上在切换Menu后把childscrollView的offest恢复成zero是更简单的做法。即刻采用的就是切换后保留childscrollView 的 offset 的做法，而包括淘票票、抖音在内的一些APP 都是在切换后直接设置成zero的做法。关于这边讨论具体可以看我博客https://bawn.github.io/2019/02/NestedScrolling/

**Comment by bawn** [comment]
@dengchenglin 现在可以通过实现 `override func keepChildScrollViewOffset(_ pageController: ShazamPageViewController) -> Bool` 方法开启和关闭切换Menu后是否要保持 offset
