### ISSUE TITLE
哎，header能响应事件的区域没法滑动  果然事事难两全

### ISSUE THREAD

**Issue by dengchenglin** [bawn/Shazam#3]

**Comment by bawn** [comment]
@dengchenglin 我博客中有提到即刻的解决方案 
https://bawn.github.io/2019/02/NestedScrolling/

>即刻为了达到完美的效果，在每个 ChildScrollView 顶部都添加了 HeaderView 和 MenuView，这样子作为一个整体，即使开始触摸的地方有可交互控件也可以上下滚动。然后在左右滑动的时又让ChildScrollView 内的 HeaderView 和 MenuView 隐藏，当停止滚动的时让原本在外层 ScrollView 内的 HeaderView 和 MenuView 显示。

或者可以看我另外一个库 [Aquaman](https://github.com/bawn/Aquaman)，header能响应事件的区域可以滑动，在切换 Menu 后 childscrollView 的 offset 也被直接设置成了 zero
