### ISSUE TITLE
设置headerView高度为0时，pageController会偏移一个屏幕的宽度

### ISSUE THREAD

**Issue by MorningStarJ** [bawn/Shazam#4]
设置headerView高度为0， reloadData后，pageController会偏移一个屏幕的宽度，滑动到尾部再次滑动就会崩溃

**Comment by bawn** [comment]
@MorningStarJ  能麻烦提供一个 Demo 吗，我不能复现 crash 的情况。但猜测你说的『偏移一个屏幕的宽度』原因是没有在子 viewcontroller 上调整相应的 headerview 的高度，至于为什么要这样子做可以看我博客中提到的 
>从整体结构上来看即刻只有二级 ScrollView，所以在纵向上 ChildScrollView 会完全接管手势，横向滚动时又由 MainScrollView 控制，这样子带来的好处在于无需关心手势冲突问题，但要实现前面提到的效果还必须处理是以下问题：
HeaderView 和 MenuView 的位置需要根据 ChildScrollView 的滚动而改变
在切换的 Tab 的时候需要同步下一个 ChildScrollView 的 offset
ChildScrollView 必须在顶部留出 HeaderView 和 MenuView 高度总和的空白区域
HeaderView 不能拦截滚动手势
